name: Build Jekyll Site with Trace

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # Allow manual trigger from GitHub UI.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify your Ruby version

      - name: Set up Python and Jupyter
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert  # Install Jupyter and nbconvert


      - name: Build with Jekyll and Trace
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build --trace
